app: familycarousel-bff
org: funkel1989

service: familycarousel-bff

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  profile: ${opt:profile, 'default'}
  memorySize: 256
  logRetentionInDays: 3
  logs:
    httpApi: true
  httpApi:
    cors: true
  stage: ${opt:stage, 'dev'}
  environment:
    NODE_ENV: ${self:provider.stage}
    AWS_PROFILE: ${self:provider.profile}
    FAMILY_SERVICE_OAUTH_CLIENTID: ${ssm:/familycarousel/${self:provider.stage}/oauth/clientid~true}
    FAMILY_SERVICE_OAUTH_CLIENTSECRET: ${ssm:/familycarousel/${self:provider.stage}/oauth/clientsecret~true}
    FAMILY_SERVICE_BASE_URL: ${self:custom.FamilyServiceUrl.${self:provider.stage}}
    FAMILY_SERVICE_AUDIENCE_URL: ${self:custom.FamilyServiceAudience.${self:provider.stage}}
    FAMILY_SERVICE_OAUTH_URL: familycarousel.auth0.com
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'logs:*'
      Resource: '*'

custom:
  FamilyServiceUrl:
    test: https://familyservice-test.familycarousel.com
    prod: https://familyservice.familycarousel.com
  FamilyServiceAudience:
    test: familyservice-test.familycarousel.com
    prod: familyservice.familycarousel.com
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    host: 0.0.0.0
  FamilyCarouselDomainMap:
    test: bff-test.familycarousel.com
    prod: bff.familycarousel.com
  FamilyCarouselCertMap:
    test: '*.familycarousel.com'
    prod: '*.familycarousel.com'
  customDomain:
    domainName: ${self:custom.FamilyCarouselDomainMap.${self:provider.stage}}
    certificateName: ${self:custom.FamilyCarouselCertMap.${self:provider.stage}}
    createRoute53Record: true
    endpointType: 'regional'
    apiType: http

package:
  individiually: true
  excludeDevDependencies: true

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-optimize

functions:
  graphql:
    name: FamilyCarousel-bff-${self:provider.stage}
    handler: handlers/handler.graphql
    description: Lambda for family carousel graphql service
    optimize: false
    events:
      - httpApi:
          path: /graphql
          method: POST
      - httpApi:
          path: /graphql
          method: GET
